name: cardio_expert
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  cloud_firestore: ^3.4.5
  # firebase_storage: ^10.3.6

  provider: ^6.0.3
  uuid: ^3.0.6
  
  # cached_network_image: ^3.2.1
  # flutter_cache_manager: ^3.3.0
  # file_picker: ^5.0.1
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/img/

  # fonts:
  #   - family: ReadexPro
  #     fonts:
  #       - asset: assets/fonts/ReadexPro-VariableFont_wght.ttf
  #   - family: DMSans
  #     fonts:
  #       - asset: assets/fonts/DMSans-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/DMSans-Regular.ttf
  #         weight: 400