name: cardio_expert
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.21.0
  firebase_auth: ^3.6.4
  cloud_firestore: ^3.4.5
  # firebase_storage: ^10.3.6

  provider: ^6.0.3
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  flutter_share: ^2.0.0
  pdf: ^3.8.3
  intl: 
  flutter_multi_formatter: ^2.5.7
  path_provider: ^2.0.11
  
  # cached_network_image: ^3.2.1
  # flutter_cache_manager: ^3.3.0
  # file_picker: ^5.0.1
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/font/
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/font/Montserrat-Regular.ttf
          weight: 500